- name: TCP port 6443 on master is reachable from worker to check if api-server is ready
  wait_for: "host={{ hostvars['master']['ansible_default_ipv4']['address'] }} port=6443 timeout=5"

- name: join cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.log"
  args:
    chdir: $HOME
    creates: node_joined.log
